Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcHouseofg.Models;

namespace MvcHouseofg.Controllers
{
    public class HomeController : Controller
    {
        private houseofgEntities db = new houseofgEntities();
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Perfil()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Catalogo()
        {
            return View(db.PRODUCTOS.ToList());
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Admin()
        {
            return View();
        }

        public ActionResult Product(int id)
        {
            Session["prod_id"] = id;
            FichaProducto p = new FichaProducto();
            p.producto = db.PRODUCTOS.FirstOrDefault(x => x.PROD_ID == id);
            List<VALORACIONES> valoraciones = db.VALORACIONES.Where(x => x.PROD_ID == id).ToList();
            p.valoracion = valoraciones;
            try
            {
                p.prom_val = db.VALORACIONES.Where(x => x.PROD_ID == id).Average(x => x.VAL_PUNTAJE);
                
                //p.valoracion = db.VALORACIONES.FirstOrDefault(y => y.PROD_ID == id);
                //PRODUCTOS p = db.PRODUCTOS.FirstOrDefault(x => x.PROD_ID == id);
            }
            catch (Exception ex)
            {

            }
            if (p != null)
            {
                ViewData.Model = p;
            }
            else
            {
                ViewBag.mensaje = "Producto no encontrado";
            }
            return View();
        }
    }
}

Controllers/ValoracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcHouseofg.Models;

namespace MvcHouseofg.Controllers
{
    public class ValoracionController : Controller
    {
        private houseofgEntities db = new houseofgEntities();
       
        public ActionResult Valorar(FichaProducto val)
        {
            if (ModelState.IsValid)
            {
                VALORACIONES valoracion = new VALORACIONES();
                valoracion.USU_ID = (String )Session["username"];
                valoracion.PROD_ID = (int)Session["prod_id"];
                //valoracion.VAL_COMENTARIO = comentario;
                //valoracion.VAL_PUNTAJE = puntaje;
                db.VALORACIONES.AddObject(valoracion);
                db.SaveChanges();
            }
            return View("../Home/Product" + Session["prod_id"]);
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
  <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <br /> <br />
                <h1 class="page-header">Sobre nosotros</h1>
                <p><strong>House of G</strong> es una empresa dedicada a la venta de perifericos gamer. </p>
                <p> A medida que los eSports (competiciones de videojuegos) han ido creciendo, los jugadores se han ido interesando más en ser parte de ellos pudiendo lograr ser un jugador profesional ya sea de estrategia en tiempo real, lucha, disparos en primera persona o de los ya conocidos MOBA. </p>
                <p>En consecuencia, se hace necesaria la utilización de periféricos que estén a la altura, mouses con más botones y respuestas mucho más rápidas, teclados mecánicos con botones programables, etc. Debido a esto y tomando en cuenta las pocas tiendas dedicadas completamente a los gamers en Arica. Queremos ser tu tienda preferida a la hora de adquirir productos de marcas conocidas como lo son Razer, Ozone, Thermaltake, entre otros para darles una alternativa con precios competitivos, ahorrándoles los costos del envío y reduciendo drásticamente el tiempo de su llegada..</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Nuestro equipo</h2>
            </div>
            <div class="col-lg-12 col-sm-12 text-center">
                <img class="img-circle img-responsive img-center" src="http://bit.ly/1pNwi1J" alt="">
                <h3>R. Fernandez
                    <small>CEO</small>
                </h3>
                <p>Informa a agentes externos la participación de la empresa, objetivos y logros de la misma, así como la gestión de la organización y los empleados.</p>
            </div>
        </div>

        <hr>

Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2>Admin</h2>
<div class="container">
    <div class="row">
         
                <div class="col-md-3">
                
                    <br />
                    <div class="list-group">
                        <a href="/Producto/Index" class="list-group-item">Gestion de Productos</a>
                    </div>
                </div> 

 </div>

Views/Home/Catalogo.cshtml
@model IEnumerable<MvcHouseofg.Models.PRODUCTOS>
@{
    ViewBag.Title = "Catalogo";
}
<br />
<br />
  <!-- Page Content -->
    <div class="container">
         <!-- Page Heading/Breadcrumbs -->
        <div class="row" >
            <div class="col-lg-12" margin:100px>
                <h1 class="page-header">House of G
                
                </h1>
                <ol class="breadcrumb">
                    <li><a href="Index">Inicio</a></li>
                    <li class="active">Productos</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
        
        
        <div class="row">
         
            <div class="col-md-3">
                <div class="list-group">
                    <a href="Catalogo" class="list-group-item">Productos</a>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="/Imagenes/@item.PROD_IMAGEN "  width="320" height="150"  alt="">
                            <div class="caption">
                                <h4 class="pull-right">@String.Format("{0:c}", item.PROD_PRECIO)</h4>
                                <h4>@Html.ActionLink(item.PROD_NOMBRE, "Product", new { id = item.PROD_ID }) </h4>
                                <p>@Html.DisplayFor(modelItem => item.PROD_DESCRIPCIONCORTA).</p>
                                <p>@Html.ActionLink("Agregar al carro", "../Carrito/AgregarCarrito", new { id = item.PROD_ID }, null) </p>
                                
                            </div>
                            
                        </div>
                    </div>
                }
                </div>

            </div>

        </div>

    </div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

 <!-- Page Content -->
    
<br /> 
<br />
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row" >
            <div class="col-lg-12" margin:100px>
                <h1 class="page-header">Contacto
                
                </h1>
                <ol class="breadcrumb">
                    <li><a href="Index">Inicio</a>
                    </li>
                    <li class="active">Contacto</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                <!-- Embedded Google Map -->
                <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://tinyurl.com/jsc8z7y"></iframe>
            </div>

            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Detalles de contacto</h3>
                <p>
                    Av. Santa María 2190<br>Arica - Chile.<br>
                </p>
                <p>
                    <button type="button" class="btn btn-default btn-sm" onclick="this.blur();">
                        <span class="glyphicon glyphicon-phone"></span> (+56 9) XXXXXXXX
                    </button>
                </p>
                <p>
                    <button type="button" class="btn btn-default btn-sm" onclick="this.blur();">
                        <span class="glyphicon glyphicon-envelope"></span>
                        <a href="mailto:nombre@ejemplo.com"> nombre@ejemplo.com</a>
                    </button>
                </p>
                <p>
                    <button type="button" class="btn btn-default btn-sm" onclick="this.blur();">
                        <span class="glyphicon glyphicon-time"></span> Lunes a Viernes: 2:00 PM a 7:00 PM
                    </button>
                </p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
        <div class="row">
            <div class="col-md-8">
                <h3>Mándenos un mensaje</h3>
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Nombre:</label>
                            <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Número de contacto:</label>
                            <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Email:</label>
                            <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Mensaje:</label>
                            <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                        </div>
                    </div>
                    <div id="success"></div>
                    <!-- For success/fail messages -->
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>

        </div>
        <!-- /.row -->

        <hr>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link href="@Url.Content("~/Content/themes/base/full-slider.css")" rel="stylesheet" type="text/css" />

Views/Home/Perfil.cshtml
@{
    ViewBag.Title = "Perfil";
}

<h2>Perfil</h2>

<div class="container">
    <div class="row">
         
                <div class="col-md-3">                
                    <br />
                    <div class="list-group">
                     @Html.ActionLink("Editar perfil", "../User/Edit", new { id = Session["username"] }, new { @class = "list-group-item" })
                     @Html.ActionLink("Cambiar contraseña", "../Account/CambiarPass", new { id = Session["username"].ToString() }, new { @class = "list-group-item" })
                     <a href="../Carrito/VerCarrito" class="list-group-item">Ver Carrito de compras</a>
                     <a href="../RedSocial" class="list-group-item">Red Social</a>
                     <a href="../RedSocial/HistorialVenta" class="list-group-item">Historial de compras</a>
                     </div>
                 </div>
 </div>

Views/Home/Product.cshtml
@model  MvcHouseofg.Models.FichaProducto
@{
    ViewBag.Title = "Product";
}
<head>
<link href="@Url.Content("~/Content/themes/base/shop-item.css")" rel="stylesheet" type="text/css" />
</head> 

<!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="row" >
            <div class="col-lg-12" margin:100px>
                <h1 class="page-header">House of G
                
                </h1>
                <ol class="breadcrumb">
                    <li><a href="Index">Inicio</a></li>
                    <li class="active">Productos</li>
                </ol>
            </div>
        </div>

           
 
             <div class="col-md-3">
                <div class="list-group">
                    <a href="../Catalogo" class="list-group-item">Productos</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="thumbnail">
                    <img class="img-responsive" src="/Imagenes/@Model.producto.PROD_IMAGEN " width="800" height="300" alt="">
                    <div class="caption-full">
                        <h4 class="pull-right">@String.Format("{0:c}",ViewData.Model.producto.PROD_PRECIO)</h4>
                        <h4><a href="#">@ViewData.Model.producto.PROD_NOMBRE</a>
                        </h4>
                        <p>Caracteristicas.</p>
                        <p>@ViewData.Model.producto.PROD_DESCRIPCIONCOMPLETA</p>
                        <p>@Html.ActionLink("Agregar al carro", "../Carrito/AgregarCarrito", new { id = Model.producto.PROD_ID }, null)</p>
                    </div>
                    <div class="ratings">
                        <span class="pull-right">@Model.valoracion.Count Comentario(s)</span>
                        <p>
                            <span>@Model.prom_val.ToString("0.0") Estrellas</span>
                        </p>
                    </div>
                </div>

                <div class="well">

                 
                            <div class="text-right">
                            @using (Html.BeginForm("Valorar", "Valoracion", FormMethod.Post,  new { enctype = "multipart/form-data" }))
                            {
                            @Html.ValidationSummary(true)
                                <div>
                                                Estrellas: @{
                                   List<SelectListItem> listItems = new List<SelectListItem>();
                                   listItems.Add(new SelectListItem
                                        {
                                            Text = "1",
                                            Value = "1"
                                        });
                                   listItems.Add(new SelectListItem
                                        {
                                            Text = "2",
                                            Value = "2",
                                            Selected = true
                                        });
                                   listItems.Add(new SelectListItem
                                        {
                                            Text = "3",
                                            Value = "3"
                                        });
                                   listItems.Add(new SelectListItem
                                   {
                                       Text = "4",
                                       Value = "4"
                                   });
                                   listItems.Add(new SelectListItem
                                   {
                                       Text = "5",
                                       Value = "5"
                                   });
                                    }

                                    @Html.DropDownListFor(model => model.val.VAL_PUNTAJE, listItems, "-- Select Status --")
                                </div>

                                <div>
                                @Html.TextAreaFor(model => model.val.VAL_COMENTARIO)
                                </div>
                                @*@Html.ActionLink("Valorar", "Valoracion", new { comentario = Model.val.VAL_COMENTARIO, puntaje = Model.val.VAL_PUNTAJE })*@

                                <input type="submit" value="Dejar comentario" />
                            }
                                @*<a href="" class="btn btn-success">Deja un comentario...</a>*@
                            </div>
                        
                    
                    <hr>
                    @foreach (var item in Model.valoracion)
                    {
                    <div class="row">
                        <div class="col-md-12">
                            <span>Usuario: @item.USU_ID</span><br />
                            <span>Valoracion: @item.VAL_PUNTAJE Estrellas</span>                            
                           <!-- <span class="pull-right">10 days ago</span> -->
                            <p>Comentario: @item.VAL_COMENTARIO</p>
                        </div>
                    </div>
                    }
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->     